### ISSUE TITLE
Example bag files and scripts

### ISSUE THREAD

**Issue by wmlynar** [mrsp/imu_ekf#1]
Hello,

great contribution, thanks. Would you mind posting

- example bag files
- example scripts

to illustrate better how to use your library?

Thanks again,
Wojciech

**Comment by mrsp** [comment]
Hello Wojciech and Merry Xmas! 

Thanks for comments.

This repo is a test repo right now, but I am refactoring the code in order to properly release it and show how to fuse kinematically computed odometry (e.g. leg odometry for humanoids, wheel odometry for mobile robots), visual odometry and/or any other pose i.e. GPS readings with the IMU readings. 

Hopefully, this will be done in about 1-2 months or so, considering we have Christmas holidays and this project is on-going research! On the other hand I'let you know that in my lab tests so far I was able to accurately estimate the 3D-pose, 3D-velocity and IMU biases for my walking humanoid robot so I am pretty confident that this filter works when properly tuned!

The EKF is based on https://groups.csail.mit.edu/rrg/papers/icra12_aggressive_flight.pdf
but with the imu biases in the state vector.

I'll leave this issue open so I can get back to you when I have the latest version. In the meanwhile, if you have any other question feel free to ask!

Thanks 

Stelios

**Comment by softdream** [comment]
Hi Stelios,
   Thanks for your great contribution.
   I noticed there was a function named loadIMUEKFparams() in the file imu_estimator.cpp. I have some questions about what should these parameters be set to. Could you please provide more details about how to set these parameters about the ekf correctly ?
   Looking forward for your reply.
   Thanks in advance.
Daofeng Du

**Comment by mrsp** [comment]
Hello 

Examples and bagfiles are posted in https://github.com/mrsp/serow

Although this is a legged robot estimator, the IMU EKF used in it is the same.

Hope it helps 
Stelios
